name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install
      - name: Run integration tests
        run: yarn test
      - name: Upload code coverage to codecov.io
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        run: |
          chmod +x ./scripts/publish-coverage.sh
          ./scripts/publish-coverage.sh ${{ secrets.CODECOV_TOKEN }}