name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install
      - name: Run integration tests
        run: yarn test

  release:
    name: Release new version
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get version
        run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags)
        id: get_version
      - name: 'npm version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
      - name: yarn install
        run: yarn install      
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}